name: Full CI/CD Pipeline (plan+apply in same runner)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    name: Build → Terraform (plan+apply) → Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------
      # Build & push Docker image
      # -------------------------
      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-ui:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-ui:${{ github.sha }}

      - name: Docker logout
        run: docker logout

      # -------------------------
      # Install Terraform CLI
      # -------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # -------------------------
      # Configure AWS
      # -------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # -------------------------
      # Terraform init + plan + apply (ALL IN SAME JOB)
      # -------------------------
      - name: Terraform init (S3 backend)
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_DYNAMODB_TABLE }}" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform fmt (check)
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan (create plan for this runner)
        run: terraform plan -out=tfplan -input=false

      - name: Terraform apply (apply the plan created above)
        run: terraform apply -input=false -auto-approve tfplan

      - name: Terraform output public_ip
        id: tfout
        run: echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

      # -------------------------
      # (Optional) Deploy step via SSH to EC2 to pull image & run container
      # -------------------------
      - name: Copy SSH private key
        run: |
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy Docker container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ steps.tfout.outputs.public_ip }} << 'EOF'
            sudo docker rm -f devops-ui 2>/dev/null || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-ui:latest
            sudo docker run -d --name devops-ui --restart unless-stopped -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/devops-ui:latest
          EOF
