name: Full CI/CD (build → plan → apply → deploy)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "ci-cd-full-${{ github.ref }}"
  cancel-in-progress: true

env:
  AWS_REGION: us-east-1
  TF_WORKING_DIR: terraform

permissions:
  contents: read

jobs:
  full-pipeline:
    name: Full pipeline — Build, Terraform, Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-ui:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-ui:${{ github.sha }}

      - name: Docker logout
        run: docker logout

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform init (S3 backend)
        working-directory: ./terraform
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_DYNAMODB_TABLE }}" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform fmt (check)
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan -input=false

      - name: Terraform apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan

      - name: Terraform output public_ip
        id: tfout
        working-directory: ./terraform
        run: echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

      - name: Write deploy private key
        run: |
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Wait for SSH on instance
        run: |
          for i in {1..15}; do
            nc -zv ${{ steps.tfout.outputs.public_ip }} 22 && break || sleep 3
          done

      - name: SSH deploy: pull image & run
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ steps.tfout.outputs.public_ip }} << 'EOF'
            sudo docker rm -f devops-ui 2>/dev/null || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-ui:latest
            sudo docker run -d --name devops-ui --restart unless-stopped -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/devops-ui:latest
          EOF
